eureka:
  instance:
    # 以IP注册到注册中心
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    # 服务的一些元数据信息
    metadata-map:
      VERSION: 0.10.0
  client:
    serviceUrl:
      # 注册中心地址，多个用逗号隔开
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://dev.hzero.org:8000/eureka}
    registryFetchIntervalSeconds: 10
    disable-delta: true

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true

choerodon:
  resource:
    pattern: /v1/*

logging:
  level:
    org.apache.ibatis: ${LOGGING_LEVEL:debug}
    io.choerodon: ${LOGGING_LEVEL:debug}
    org.hzero: ${LOGGING_LEVEL:debug}

#spring:
#  cloud:
#    inetutils:
#      # 本地多网卡时，忽略回环网卡
#      ignored-interfaces[0]: lo
#      # 本地多网卡时，选择注册的网段
#      preferred-networks[0]: xx.xx

spring:
  application:
    name: hzero-todo-service